---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  labels:
    app: ecommerce
    service: cart
spec:
  replicas: 2
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      service: cart
  template:
    metadata:
      labels:
        app: ecommerce
        service: cart
    spec:
      containers:
      - name: cart
        image: microbs-ecommerce-cart
        imagePullPolicy: IfNotPresent
        readinessProbe:
          httpGet:
            port: 80
            path: /healthz
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 5
        env:
        - name: SERVICE_NAME
          value: cart
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: pod=$(POD_NAME)
        envFrom:
        - secretRef:
           name: microbs-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: cart
  labels:
    app: ecommerce
    service: cart
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    service: cart
