---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-data
  labels:
    app: ecommerce
    service: product-data
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      service: product-data
  template:
    metadata:
      labels:
        app: ecommerce
        service: product-data
    spec:
      containers:
      - name: product-data
        image: microbs-ecommerce-product-data
        imagePullPolicy: IfNotPresent
        readinessProbe:
          exec:
            command:
            - bash
            - "-c"
            - |
              psql --username "$POSTGRES_USER" --dbname "products" -c "SELECT 1"
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 5
        resources:
          limits:
           cpu: 500m
           memory: 128Mi
          requests:
           cpu: 100m
           memory: 128Mi
        envFrom:
        - secretRef:
            name: microbs-secrets
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: password
        - name: SERVICE_VERSION
          value: $(DEPLOYMENT_VERSION)
---
apiVersion: v1
kind: Service
metadata:
  name: product-data
  labels:
    app: ecommerce
    service: product-data
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    service: product-data
