---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: synthetics
  labels:
    app: ecommerce
    service: synthetics
spec:
  replicas: 2
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      service: synthetics
  template:
    metadata:
      labels:
        app: ecommerce
        service: synthetics
    spec:
      containers:
      - name: synthetics
        image: microbs-ecommerce-synthetics
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        env:
        - name: SERVICE_NAME
          value: synthetics
        envFrom:
        - secretRef:
           name: microbs-secrets
