---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: synthetics
  labels:
    app: synthetics
spec:
  replicas: 2
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: synthetics
  template:
    metadata:
      labels:
        app: synthetics
    spec:
      containers:
      - name: synthetics
        image: microbs-ecommerce-synthetics
        imagePullPolicy: IfNotPresent
        env:
        - name: SERVICE_NAME
          value: synthetics
        envFrom:
        - secretRef:
           name: microbs-secrets
