---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout
  labels:
    app: ecommerce
    service: checkout
spec:
  replicas: 2
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      service: checkout
  template:
    metadata:
      labels:
        app: ecommerce
        service: checkout
    spec:
      containers:
      - name: checkout
        image: microbs-ecommerce-checkout
        imagePullPolicy: IfNotPresent
        readinessProbe:
          httpGet:
            port: 80
            path: /healthz
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 5
        env:
        - name: SERVICE_NAME
          value: checkout
        - name: SERVICE_HOST_API_GATEWAY
          value: api-gateway
        - name: SERVICE_PORT_API_GATEWAY
          value: "80"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: pod=$(POD_NAME)
        envFrom:
        - secretRef:
           name: microbs-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: checkout
  labels:
    app: ecommerce
    service: checkout
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    service: checkout
