---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout
  labels:
    app: ecommerce
    service: checkout
spec:
  replicas: 2
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      service: checkout
  template:
    metadata:
      labels:
        app: ecommerce
        service: checkout
    spec:
      containers:
      - name: checkout
        image: microbs-ecommerce-checkout
        imagePullPolicy: IfNotPresent
        readinessProbe:
          httpGet:
            port: 80
            path: /healthz
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 5
        env:
        - name: SERVICE_HOST_API_GATEWAY
          value: api-gateway
        - name: SERVICE_PORT_API_GATEWAY
          value: "80"
        - name: SERVICE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['service']
        - name: K8S_APP
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['app']
        - name: K8S_NAMESPACE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: K8S_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: K8S_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: K8S_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: k8s.app=$(K8S_APP),k8s.namespace.name=$(K8S_NAMESPACE_NAME),k8s.node.name=$(K8S_NODE_NAME),k8s.pod.ip=$(K8S_POD_IP),k8s.pod.name=$(K8S_POD_NAME)
        envFrom:
        - secretRef:
           name: microbs-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: checkout
  labels:
    app: ecommerce
    service: checkout
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    service: checkout
