---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: templates
    service: api-gateway
spec:
  replicas: 2
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      service: api-gateway
  template:
    metadata:
      labels:
        app: templates
        service: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: microbs-templates-api-gateway
        imagePullPolicy: IfNotPresent
        readinessProbe:
          httpGet:
            port: 8080
            path: /healthz
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 5
        env:
        - name: SERVICE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['service']
        - name: K8S_APP
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['app']
        - name: K8S_NAMESPACE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: K8S_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: K8S_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: k8s.app=$(K8S_APP),k8s.namespace.name=$(K8S_NAMESPACE_NAME),k8s.node.name=$(K8S_NODE_NAME),k8s.pod.name=$(K8S_POD_NAME)
        envFrom:
        - secretRef:
           name: microbs-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  labels:
    app: templates
    service: api-gateway
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    service: api-gateway
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-external
  labels:
    app: templates
spec:
  type: LoadBalancer
  selector:
    service: api-gateway
  ports:
  - name: http
    port: 8080
    targetPort: 8080
