---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
  labels:
    app: product
spec:
  replicas: 2
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
      - name: product
        image: microbs-ecommerce-product
        imagePullPolicy: IfNotPresent
        readinessProbe:
          httpGet:
            port: 80
            path: /healthz
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 5
        env:
        - name: SERVICE_NAME
          value: product
        - name: SERVICE_HOST_PRODUCT_DATA
          value: product-data
        - name: SERVICE_PORT_PRODUCT_DATA
          value: "5432"
        - name: SERVICE_USERNAME_PRODUCT_DATA
          value: postgres
        - name: SERVICE_PASSWORD_PRODUCT_DATA
          value: password
        envFrom:
        - secretRef:
           name: microbs-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: product
  labels:
    app: product
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: product
