apiVersion: skaffold/v2beta27
kind: Config
build:
  tagPolicy:
    customTemplate:
      template: "{{.GIT_COMMIT}}"
      components:
      - name: GIT_COMMIT
        gitCommit: {}
profiles:
- name: main
  build:
    artifacts:
    - image: microbs-templates-api-gateway
      context: ./apps/templates
      docker:
        dockerfile: services/api-gateway/Dockerfile
    - image: microbs-templates-nginx
      context: ./apps/templates
      docker:
        dockerfile: services/nginx/Dockerfile
    - image: microbs-templates-python-flask
      context: ./apps/templates
      docker:
        dockerfile: services/python-flask/Dockerfile
  deploy:
    kubectl:
      manifests:
      - ./apps/templates/services/*/k8s/*.yaml
