apiVersion: skaffold/v2beta27
kind: Config
build:
  tagPolicy:
    customTemplate:
      template: "{{.GIT_COMMIT}}"
      components:
      - name: GIT_COMMIT
        gitCommit: {}
profiles:
- name: main
  build:
    artifacts:
    - image: microbs-templates-nginx
      context: ./apps/templates/services/nginx
    - image: microbs-templates-nodejs-express
      context: ./apps/templates/services/nodejs-express
    - image: microbs-templates-python-flask
      context: ./apps/templates/services/python-flask
  deploy:
    kubectl:
      manifests:
      - ./apps/templates/services/nginx/k8s/*.yaml
      - ./apps/templates/services/nodejs-express/k8s/*.yaml
      - ./apps/templates/services/python-flask/k8s/*.yaml
