{
 "title": "Services Overview",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "percentile", "label": "Percentile", "query": ".50, .75, .90, .95, .99, 1.0" },
   { "name": "services", "label": "Services", "query": { "query": "label_values(service_name)" } },
   { "name": "operations", "label": "Operations", "query": { "query": "label_values(operation)" } }
  ]
 },
 "panels": [
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Latency by Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum(rate(traces_spanmetrics_latency_bucket{service_name=~\"$services\",operation=~\"$operations\"}[1m])) by(le, service_name)) * 1",
     "legendFormat": "{{service_name}}"
    },
    {
     "expr": "histogram_quantile($percentile, sum(rate(traces_spanmetrics_latency_bucket{service_name=~\"$services\",operation=~\"$operations\"}[1m])) by (le)) * 1",
     "legendFormat": "(average)"
    }
   ]
  },
  {
   "title": "Throughput by Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(traces_spanmetrics_calls_total_total{service_name=~\"$services\",operation=~\"$operations\"}[10s])) by (service_name)",
     "legendFormat": "{{ service_name }}"
    },
    {
     "expr": "sum(sum(rate(traces_spanmetrics_calls_total_total{service_name=~\"$services\",operation=~\"$operations\"}[10s])) by (service_name))",
     "legendFormat": "(total)"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Logs - Errors & Warnings",
   "type": "logs",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{cluster=\"microbs\",k8s_container_name=~\"$services\",k8s_app!=\"grafana-agent\"} | logfmt != \"healthz\" |~ \"critical|Critical|CRITICAL|error|Error|ERROR|exception|Exception|EXCEPTION|fail|Fail|FAIL|fatal|Fatal|FATAL|warn|Warn|WARN\""
    }
   ]
  },
  {
   "title": "Logs - All",
   "type": "logs",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "{cluster=\"microbs\",k8s_container_name=~\"$services\",k8s_app!=\"grafana-agent\"} | logfmt != \"healthz\""
    }
   ]
  }
 ]
}