---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-data
  labels:
    app: ecommerce
    service: session-data
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      service: session-data
  template:
    metadata:
      labels:
        app: ecommerce
        service: session-data
    spec:
      subdomain: session-data
      containers:
      - name: session-data
        image: microbs-ecommerce-session-data
        imagePullPolicy: IfNotPresent
        command:
          - "redis-server"
        args:
          - "--dir"
          - "/data"
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 5
        resources:
          limits:
           cpu: 500m
           memory: 128Mi
          requests:
           cpu: 100m
           memory: 64Mi
        envFrom:
        - secretRef:
           name: microbs-secrets
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-data-replica
  labels:
    app: ecommerce
    service: session-data-replica
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      service: session-data-replica
  template:
    metadata:
      labels:
        app: ecommerce
        service: session-data-replica
    spec:
      subdomain: session-data-replica
      containers:
      - name: session-data-replica
        image: microbs-ecommerce-session-data
        imagePullPolicy: IfNotPresent
        command:
          - "redis-server"
        args:
          - "--dir"
          - "/data"
          - "--slaveof"
          - "session-data.default.svc.cluster.local"
          - "6379"
          - "--protected-mode"
          - "no"
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 5
        resources:
          limits:
           cpu: 500m
           memory: 128Mi
          requests:
           cpu: 100m
           memory: 64Mi
        envFrom:
        - secretRef:
           name: microbs-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: session-data
  labels:
    app: ecommerce
    service: session-data
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    service: session-data
---
apiVersion: v1
kind: Service
metadata:
  name: session-data-replica
  labels:
    app: ecommerce
    service: session-data-replica
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    service: session-data-replica
