---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-flask
  labels:
    app: python-flask
spec:
  replicas: 2
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-flask
  template:
    metadata:
      labels:
        app: python-flask
    spec:
      containers:
      - name: python-flask
        image: microbs-templates-python-flask
        imagePullPolicy: IfNotPresent
        readinessProbe:
          httpGet:
            port: 80
            path: /healthz
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 5
        env:
        - name: SERVICE_NAME
          value: python-flask
        envFrom:
        - secretRef:
           name: microbs-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: python-flask
  labels:
    app: python-flask
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: python-flask
