# Build and test whenever pushing a commit or submitting a pull request
name: Commit
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - "v*.*.*"
      - "v*.*.*-*"
  pull_request:
    branches:
      - '**'
    tags-ignore:
      - "v*.*.*"
      - "v*.*.*-*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04

    # Attempt to run all tests
    strategy:
      fail-fast: false

    steps:

      # Install node
      - name: Setup node
        uses: actions/setup-node@v2

      # Checkout the repository
      # Uses: https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v2

      # Install
      - name: Install dependencies
        run: npm ci

      # Test
      - name: Run tests
        run: npm run test
