# Build, test, and deploy whenever pushing a release tag
name: Deploy
on:
  push:
    tags:
      - "v*.*.*"
      - "v*.*.*-*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04

    # Attempt to run all tests
    strategy:
      fail-fast: false

    steps:

      # Install node
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          registry-url: 'https://registry.npmjs.org'
          scope: '@microbs.io'

      # Checkout the repository
      # Uses: https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v2

      # Install
      - name: Install dependencies
        run: npm ci

      # Test
      - name: Run tests
        run: npm run test
        
  create_release:
    name: Create release
    needs: build

    # Use the latest LTS OS
    runs-on: ubuntu-20.04
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      release_tag: ${{ steps.get_tag.outputs.tag }}
    steps:

      # Checkout the repository
      # Uses: https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v2

      # Get the release tag
      - name: Get release tag
        id: get_tag
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      # Create the release
      # Uses: https://github.com/actions/create-release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') || contains(github.ref, 'rc') || contains(github.ref, 'experimental') }}
          body: "Releasing ${{ steps.get_tag.outputs.tag }}"
          
  publish_to_npmjs:
    name: Publish to npmjs
    needs: create_release
    
    runs-on: ubuntu-20.04
    steps:
      
      # Checkout the repository
      # Uses: https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v2
        
      # Install node
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          registry-url: 'https://registry.npmjs.org'
          scope: '@microbs.io'
          
      # Install
      - name: Install dependencies
        run: npm ci
          
      # Publish
      - name: Publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
