---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: synthetics
  labels:
    app: ecommerce
    service: synthetics
spec:
  replicas: 6
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      service: synthetics
  template:
    metadata:
      labels:
        app: ecommerce
        service: synthetics
    spec:
      containers:
      - name: synthetics
        image: microbs-ecommerce-synthetics
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "1"
            memory: 128Mi
        env:
        - name: SERVICE_NAME
          value: synthetics
        - name: NUM_VIRTUAL_USERS
          value: "150"
        envFrom:
        - secretRef:
           name: microbs-secrets
